# Generated by Django 5.2 on 2025-04-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField()),
                ('ratings', models.FloatField(default=0)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Mobile Phones', 'Mobile Phones'), ('Laptops', 'Laptops'), ('Accessories', 'Accessories'), ('Headphones', 'Headphones'), ('Food', 'Food'), ('Books', 'Books'), ('Clothes/Shoes', 'Clothes/Shoes'), ('Beauty/Health', 'Beauty/Health'), ('Sports', 'Sports'), ('Outdoor', 'Outdoor'), ('Home', 'Home')], max_length=50)),
                ('seller', models.CharField(max_length=255)),
                ('stock', models.PositiveIntegerField()),
                ('num_of_reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
